# 使用 Ubuntu 作为基础镜像
FROM ubuntu:22.04

# 定义构建参数（必须在此处声明才能被后续指令使用）
ARG condaEnv=${condaEnv}

# 安装依赖：curl 和 bzip2 用于安装 Miniconda
RUN apt-get update && \
    apt-get install -y wget curl bzip2 && \
    rm -rf /var/lib/apt/lists/*

# 安装 Miniconda
RUN echo "install miniconda"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm -f miniconda.sh

# 设置 Conda 环境变量，确保 conda 可用
ENV PATH="/opt/conda/bin:$PATH"


# 复制并解压 Conda 环境（必须使用 `conda pack` 生成的压缩包）
COPY ${condaEnv}.tar.gz /opt/conda/envs/
RUN mkdir -p /opt/conda/envs/${condaEnv} && \
    tar -xzf /opt/conda/envs/${condaEnv}.tar.gz -C /opt/conda/envs/${condaEnv} && \
    rm /opt/conda/envs/${condaEnv}.tar.gz


# 安装 mysql-connector-python
#RUN conda run -n ai_sec_test pip install mysql-connector-python -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN echo "install mysql-connector-python"
RUN conda run -n ${condaEnv} conda install pymysql

# 安装shap和sklearn
RUN echo "install shap==0.47.2 and scikit-learn==1.5.0"
RUN conda run -n ${condaEnv} pip install shap==0.47.2 scikit-learn==1.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
# 安装requests
RUN echo "install requests==2.32.3"
RUN conda run -n ${condaEnv} pip install requests==2.32.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
# 安装matplotlib
RUN echo "install matplotlib==3.9.0"
RUN conda run -n ${condaEnv} pip install matplotlib==3.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
# 扰动攻击环境需要
# 安装scikit-image
RUN echo "install scikit-image"
RUN conda run -n ${condaEnv} pip install scikit-image -i https://pypi.tuna.tsinghua.edu.cn/simple
# 安装wand
RUN echo "install Wand"
RUN apt-get update && \
    apt-get install -y imagemagick libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*
RUN conda run -n ${condaEnv} pip install Wand -i https://pypi.tuna.tsinghua.edu.cn/simple
# 安装cv2
RUN echo "install opencv-python"
RUN conda run -n ${condaEnv} pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple

# 激活 Conda 环境并安装依赖（使用 pip）
# 先升级 pip 避免版本过旧导致安装问题
RUN echo "Install required packages via pip" \
    conda run -n ${condaEnv} pip install --upgrade pip \
    -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    conda run -n ${condaEnv} pip install \
        adversarial-robustness-toolbox \
        packaging \
        pyyaml \
        -i https://pypi.tuna.tsinghua.edu.cn/simple



# 设置工作目录
WORKDIR /app

# 默认命令
CMD ["bash", "-c", "sleep 86400"]